CREATE DATABASE budget IF NOT EXISTS;

USE budget;

CREATE TABLE items (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description TEXT NOT NULL,
  price FLOAT NOT NULL
);